PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Updated test event",
    "description": "A updated test event",
    "location": "A updated test location",
    "dateTime": "2025-01-01T15:30:00.00Z"
}
